language: ruby
rvm:
  - 2.0.0

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 1 # give xvfb some time to starta
  - "ln -s www mobile"
  - "ruby -run -e httpd . -p 3000 &"
  - sleep 1

script: "bundle exec rspec spec/"

